### PR TITLE
Service Declaration Bugfix for Standard Sales Lines + Standard Purchase Lines

### PR DESCRIPTION
**Pull request by pri-kise**
Fixes Issues with Standard Purchase Lines + Standard Sales Lines

Follow-Up for: https://github.com/microsoft/ALAppExtensions/pull/25223

Steps to Reproduce the issue:
- Create a Docker Environment for BC23.2
- Create a new Item of Type Service
- Enable the Service Declaration by creating a Service Declaration Setup Record
- Move to a Customer and add Standard Sales Lines (Set them to automatic for Sales Orders)
- Add one Standard Sales Line for the new created Item of Type Service
- Use the action to create a new sales order
- Add an addtional line for the Item manually
- Check the create sales order lines and compare the field "Applicable For Serv. Decl."

Sales Line created from Standard Sales Line
image

Manually entered Sales Line:
image

Related Issues:
- https://github.com/microsoft/ALAppExtensions/issues/25222
- https://github.com/microsoft/ALAppExtensions/issues/25700
Fixes AB#496936

### CODE REVIEW

**Comment by VolodySyn** [comment]
There is a bug on our side on screenshot 1. Since Customer's country code is empty (local country), Applicable for Serv. Decl. must be false. Working on a fix. 
Thank you for reporting the issue!

**Comment by JesperSchulz** [comment]
@pri-kise, with this info, do you still need this PR?

**Comment by VolodySyn** [comment]
@JesperSchulz @pri-kise yes, we need both changes - use GetSalesHeader() as suggested, and empty country fix

**Review by JesperSchulz — APPROVED** [review]

**Review by VolodySyn — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.

**Pull request merged**
