### PR TITLE
GP migration - Hotfix for email and item transaction issues

### PR DESCRIPTION
**Pull request by jaymckinney-enavate**
This PR contains the following fixes to the GP migration.
- Corrects a previous merge issue regarding the setting of email addresses for Customers and Vendors.
- "mailto:" will automatically be stripped from email addresses.
- Empty item transactions are now skipped.
- Increased the item transaction batch size and reduced the batch name prefix to allow for more item transactions.
Fixes AB#497954

### CODE REVIEW

**Review by nikolakukrika — DISMISSED** [review]

**Comment by JesperSchulz** [comment]
Looks like we've got a few failing tests:


```
  Error: Function TestGPCustomerImport Assert.AreEqual failed. Expected:<GoodEmailAddress@testing.tst;support@testing.tst> (Text). Actual:<goodemailaddress@testing.tst;support@testing.tst> (Text). E-Mail of Migrated Customer is wrong.
      Testfunction TestGPCustomerImport Failure (0.883 seconds)
        Error:
          Assert.AreEqual failed. Expected:<GoodEmailAddress@testing.tst;support@testing.tst> (Text). Actual:<goodemailaddress@testing.tst;support@testing.tst> (Text). E-Mail of Migrated Customer is wrong.
        Call Stack:
          Assert(CodeUnit 130000).AreEqual line 3 - Tests-TestLibraries by Microsoft
          GP Data Migration Tests(CodeUnit 139664).TestGPCustomerImport line 127 - Dynamics GP Intelligent Cloud Tests by Microsoft
          Test Runner - Mgt(CodeUnit 130454).RunTests line 21 - Test Runner by Microsoft
          Test Runner - Isol. Codeunit(CodeUnit 130450).OnRun(Trigger) line 4 - Test Runner by Microsoft
          Test Suite Mgt.(CodeUnit 130456).RunTests line 2 - Test Runner by Microsoft
          Test Suite Mgt.(CodeUnit 130456).RunSelectedTests line 35 - Test Runner by Microsoft
          Test Suite Mgt.(CodeUnit 130456).RunNextTest line 20 - Test Runner by Microsoft
          Command Line Test Tool(Page 130455).RunNextTest - OnAction(Trigger) line 7 - Test Runner by Microsoft
```


```
  Error: Function TestEmailAddressSelection Assert.AreEqual failed. Expected:<longeremailaddressshouldnotbeselected@test.net;ANOTHEREMAILADDRESS@test.net;shortemail@test.net> (Text). Actual:<longeremailaddressshouldnotbeselected@test.net;anotheremailaddress@test.net;shortemail@test.net> (Text). Incorrect multiple email text. (100 max length).
      Testfunction TestEmailAddressSelection Failure (0.003 seconds)
        Error:
          Assert.AreEqual failed. Expected:<longeremailaddressshouldnotbeselected@test.net;ANOTHEREMAILADDRESS@test.net;shortemail@test.net> (Text). Actual:<longeremailaddressshouldnotbeselected@test.net;anotheremailaddress@test.net;shortemail@test.net> (Text). Incorrect multiple email text. (100 max length).
        Call Stack:
          Assert(CodeUnit 130000).AreEqual line 3 - Tests-TestLibraries by Microsoft
          GP Data Migration Tests(CodeUnit 139664).TestEmailAddressSelection line 25 - Dynamics GP Intelligent Cloud Tests by Microsoft
          Test Runner - Mgt(CodeUnit 130454).RunTests line 21 - Test Runner by Microsoft
          Test Runner - Isol. Codeunit(CodeUnit 130450).OnRun(Trigger) line 4 - Test Runner by Microsoft
          Test Suite Mgt.(CodeUnit 130456).RunTests line 2 - Test Runner by Microsoft
          Test Suite Mgt.(CodeUnit 130456).RunSelectedTests line 35 - Test Runner by Microsoft
          Test Suite Mgt.(CodeUnit 130456).RunNextTest line 20 - Test Runner by Microsoft
          Command Line Test Tool(Page 130455).RunNextTest - OnAction(Trigger) line 7 - Test Runner by Microsoft
```


```
  Error: Function TestGPVendorImport Assert.AreEqual failed. Expected:<GoodEmailAddress@testing.tst> (Text). Actual:<goodemailaddress@testing.tst> (Text). Vendor primary address email was not set correctly..
      Testfunction TestGPVendorImport Failure (1.796 seconds)
        Error:
          Assert.AreEqual failed. Expected:<GoodEmailAddress@testing.tst> (Text). Actual:<goodemailaddress@testing.tst> (Text). Vendor primary address email was not set correctly..
        Call Stack:
          Assert(CodeUnit 130000).AreEqual line 3 - Tests-TestLibraries by Microsoft
          GP Data Migration Tests(CodeUnit 139664).TestGPVendorImport line 206 - Dynamics GP Intelligent Cloud Tests by Microsoft
          Test Runner - Mgt(CodeUnit 130454).RunTests line 21 - Test Runner by Microsoft
          Test Runner - Isol. Codeunit(CodeUnit 130450).OnRun(Trigger) line 4 - Test Runner by Microsoft
          Test Suite Mgt.(CodeUnit 130456).RunTests line 2 - Test Runner by Microsoft
          Test Suite Mgt.(CodeUnit 130456).RunSelectedTests line 35 - Test Runner by Microsoft
          Test Suite Mgt.(CodeUnit 130456).RunNextTest line 20 - Test Runner by Microsoft
          Command Line Test Tool(Page 130455).RunNextTest - OnAction(Trigger) line 7 - Test Runner by Microsoft
```

**Comment by jaymckinney-enavate** [comment]
I’ll get them corrected soon.

Jay

**Comment by jaymckinney-enavate** [comment]
I committed a fix and all tests pass now.

From: Jay McKinney
Sent: Wednesday, January 31, 2024 8:22 AM
To: microsoft/ALAppExtensions ***@***.***>; microsoft/ALAppExtensions ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [microsoft/ALAppExtensions] GP migration - Hotfix for email and item transaction issues (PR #25777)

I’ll get them corrected soon.

Jay

**Comment by JesperSchulz** [comment]
This has been processed internally by Nikola. I will attempt to merge this PR.

**Review by JesperSchulz — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 15908.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15885.

**Pull request merged**
