### PR TITLE
#12520 test on unique mail in lowercase to avoid collation issues

### PR DESCRIPTION
**Pull request by fvet**
Cfr #12520 

@darjoo

### CODE REVIEW

**Review by darjoo — APPROVED** [review]

**Comment by darjoo** [comment]
I'll merge it once I've processed it internally :)

**Comment by darjoo** [comment]
Small modification made. Only setting the key to lowercase, such that it keeps the casing that's used.
This was because our internal tests all depended on retrieving the exact same email (case-sensitive) back.

Merging the PR once the build succeeds.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.

**Pull request merged**
