### PR TITLE
#15409: Lock 'SignaturePlaceHolderLbl' to avoid translation

### PR DESCRIPTION
**Pull request by hemisphera**
#15409

### CODE REVIEW

**Review by mazhelez — APPROVED** [review]
Nice catch!

Thank you for contributing the fix :)

**Review by darjoo — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.

**Comment by hemisphera** [comment]
Hi Jesper,

your last response was 14 days ago - at that time the "next update for
release 19" would have been BC19.02 which came out and does not yet contain
the fix. We have a customer that is waiting on this. Will this come with
BC19.03? Do you have any ETA?

Thanks

**Comment by JesperSchulz** [comment]
The change went in on the 2nd of December and will hence ship with the January update, which is 2021 Wave II Update 3. As a rule of thumb, we branch for the upcoming monthly minor in the last week before the upcoming month and the update releases early in the month. Occasionally, internal or external issues prevent us from releasing at the planned time, but the release still remains locked for additions other than those which will resolve the release issues.

**Pull request merged**
