### PR TITLE
Fixed app description for Sumango Autobank.

### PR DESCRIPTION
**Pull request by Saras-Sumango**
Changed AppDescription for Sumango Autobank in ConnectivityAppDefinitions.Codeunit.al.

### CODE REVIEW

**Comment by Saras-Sumango** [comment]
@microsoft-github-policy-service agree [company="Sumango AS"]

**Comment by Saras-Sumango** [comment]
v@microsoft-github-policy-service agree company="Sumango AS"

**Comment by Saras-Sumango** [comment]
@microsoft-github-policy-service agree company="Sumango AS"

**Comment by haoranpb** [comment]
Need a vote from @sorenfriisalexandersen before pushing the changes

**Review by sorenfriisalexandersen — DISMISSED** [review]

**Review by haoranpb — APPROVED** [review]

**Pull request closed without merging**
