### PR TITLE
add procedure GenerateBase64KeyedHash

### PR DESCRIPTION
**Pull request by MiguelMercadoActual**
In the codeunit "Cryptography Management" you have the following methods:

• GenerateHash
• GenerateHashAsBase64String
• GenerateBase64KeyedHashAsBase64String

But we are missing the method: GenerateBase64KeyedHash that receives the key in base64 but that the hash does not convert it to base64.

### CODE REVIEW

**Comment by JesperSchulz** [comment]
@MiguelMercadoActual, could you sign the CLA, then we can start processing your PR :-)

**Comment by MiguelMercadoActual** [comment]
@JesperSchulz Sign the CLA Done!

**Comment by PredragMaricic** [comment]
Looks good, but we need tests in order to be able to submit. Can you please ensure proper coverage ?

**Review by PredragMaricic — COMMENTED** [review]
Please create some test automation

**Comment by MiguelMercadoActual** [comment]
@PredragMaricic I already updated the test!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Reopening, as this PR should get merged, rather than closed. Expected release is with 18.4.

**Comment by MiguelMercadoActual** [comment]
@JesperSchulz that's really fine, thanks for you suport!!!

**Review by JesperSchulz — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Thanks for chipping in! :-)
Will wait with merging until our 18.3 bits and pieces have been merged. As this releases with 18.4, the changes would get "swallowed" with our 18.3 update. Once 18.3 has been merged, this one gets merged to. No more actions needed on this PR :-)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.

**Pull request merged**
