### PR TITLE
Update ConnectivityAppDefinitions.Codeunit.al

### PR DESCRIPTION
**Pull request by lukasaus**
Three new qualifying countries added: ES, FI, LV.

As per statistics:
image

Fixes AB#498782

### CODE REVIEW

**Comment by sorenfriisalexandersen** [comment]
@lukasaus I am sorry, but we cannot yet confirm the 3 customers in ES and FI. I suspect this has to do with our own refresh of the data (currently looking at data that is 22 days old). Let me see if we can get it refreshed on our side so we see the same. Stay tuned.

@JesperSchulz @haoranpb This PR is fine in theory - just need to be able to confirm the numbers before we approve.

**Comment by sorenfriisalexandersen** [comment]
@lukasaus I can confirm ES and LV now, but I still don't see any installs in FI, even when looking at fresh telemetry from yesterday.
Could you send me the tenant ID's in an email, so I can look into it? Thanks.

@JesperSchulz FYI

**Review by sorenfriisalexandersen — APPROVED** [review]

**Review by JesperSchulz — APPROVED** [review]

**Comment by sorenfriisalexandersen** [comment]
[heart]         Søren Alexandersen reacted to your message:
________________________________

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15971.

**Pull request merged**
