### PR TITLE
Update RecurrenceScheduleCard.Page.al

### PR DESCRIPTION
**Pull request by RadekMiernik**
Typo fixed.

### CODE REVIEW

**Review by darjoo — APPROVED** [review]

**Comment by darjoo** [comment]
Hi @radekmiernik, nice catch on that. 
However we're unable to make that is a breaking change unless we obsolete it first and create a replacement with preprocessor tags.

`#if CLEAN19
...
#elseif
...`

**Comment by RadekMiernik** [comment]
I am totally aware of it. I just want to point out this typo, and I know that a pull request is the best way to 'not to forget about something.

**Comment by pri-kise** [comment]
@darjoo is this really a breaking change, since this page is set to `extensible=false`?
https://github.com/microsoft/ALAppExtensions/blob/5c490ab80d8f5c4ac26641604eba79dbe1b1eb47/Modules/System/Recurrence%20Schedule/src/RecurrenceScheduleCard.Page.al#L11

**Comment by JesperSchulz** [comment]
This one indeed shouldn't be breaking. Let's hope our build system agrees ;-) This should be able to go in "as is".

**Review by JesperSchulz — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.

**Pull request merged**
