### PR TITLE
BCPT: Added DrilldownPageId

### PR DESCRIPTION
**Pull request by lvanvugt**
As per #9719 I am providing tis PR to get it added to the MS master.

### CODE REVIEW

**Comment by JesperSchulz** [comment]
I will forward this PR to our BCPT team :-) They should get back to you soon!

**Comment by JesperSchulz** [comment]
I am assuming on the changes in file Modules/DevTools/BusinessCentralPerformanceToolkit/src/BCPTLogEntry.Table.al belong to this PR?

**Comment by JesperSchulz** [comment]
The other two are in a different PR as well. Will revert those changes in this PR for you :-)

**Review by JesperSchulz — APPROVED** [review]

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 17.

**Pull request merged**
