### PR TITLE
[Shopify] - Add Item As Variant Tests

### PR DESCRIPTION
**Pull request by tinestaric**
This pull request does not have a related issue as it's part of delivery for development agreed directly with @AndreiPanko
Fixes #26819

### Add Item As Variant Test

Automated tests for changes #26712 

Fixes [AB#555979](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555979)

### CODE REVIEW

**Review by onbuyuka — APPROVED** [review]

**Comment by JesperSchulz** [comment]
@petemchlk, this PR has been processed internally. Now we just need to merge this one. Could you pull from main to make CI pass please?

**Comment by petemchlk** [comment]
@JesperSchulz done :)

**Review by JesperSchulz — APPROVED** [review]

**Review by dawidwoz — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26251.

**Pull request merged**
