### PR TITLE
GP to BC migration Last Reconciled Balance

### PR DESCRIPTION
**Pull request by ToddE123**
Moving the GP Last Reconciled Balance amount from Bank account's "Balance Last Statement" to proper general journal entry.

### CODE REVIEW

**Review by nikolakukrika — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.5.

Build ID to track: 45681.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 45682.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 45691.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45683.

**Pull request merged**
