### PR TITLE
Added x-ms-blob-content-type to "ABS Optional Parameters"

### PR DESCRIPTION
**Pull request by Arthurvdv**
Make it possible to set the blob’s content type, releated to issue https://github.com/microsoft/ALAppExtensions/issues/22142.

image
https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob?tabs=azure-ad#request-headers-all-blob-types

### CODE REVIEW

**Comment by JesperSchulz** [comment]
@pri-kise, you seem to have been involved in the discussions in #22142. Could you do a swift review of this PR?

**Comment by pri-kise** [comment]
I don't think that this is quite the right approach.
If I read the documenation correctly, then my rollback in PR #24233 should fix the header `Content-Type` and then this change here isn't needed.

>If the client specifies a standard HTTP header, but not the custom property header, the value is stored in the corresponding custom property that's associated with the blob, and it's returned by a call to Get Blob Properties. For example, if the client sets the Content-Type header on the request, that value is stored in the blob's x-ms-blob-content-type property.

see: _https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob?tabs=azure-ad#remarks_

**Comment by JesperSchulz** [comment]
@Arthurvdv, could you verify? And if you agree, please close this PR.

**Comment by JesperSchulz** [comment]
I will close this PR, assuming it isn't needed. @Arthurvdv, if you need this after all, please don't hesitate to reopen this PR and we will look at it again!

**Pull request closed without merging**
