### PR TITLE
Fix typos 

### PR DESCRIPTION
**Pull request by tfenster**
Just a couple of typos that jumped out at me

### CODE REVIEW

**Comment by JesperSchulz** [comment]
Nice one :) We'll be on it.

**Review by JesperSchulz — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Code is getting submitted to master branch in our internal build system now. Will get backported to 17.x tomorrow. These changes will ship with 17.3 in January.

**Comment by tfenster** [comment]
Thanks! Very impressive turnaround time 👍

**Comment by JesperSchulz** [comment]
Had to rename the test file as well. CodeCop complained about mismatch between object and file name. But now it's in. Issue closed :-)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for releasee 17.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Pull request merged**
