### PR TITLE
[Shopify] Shpfy access level

### PR DESCRIPTION
**Pull request by louagej**
### Access Property

In order to promote extensibility of the Shopify connector, removed Access = Internal Property

### CODE REVIEW

**Comment by pri-kise** [comment]
@louagej  you removed the Access Property from serveral tables.
In the issue you only mention **Table 30107 "Shpfy Customer Template"**.

Could you please elaborate these changes or revert the other changes.

The shopify module is made on purpose as internal to provide access only for specified processes.

If you need access to specific table or objects then please provide an exmaple or a business need for the relevant objects.

**Comment by louagej** [comment]
@pri-kise ,

If tables are set to Access = Internal, you can't even use the as a variable in your code, or subscribe to any insert, modify or delete.
That's why I think this access level should be removed.
Any other isv trying to develop custom functionality for their customers will take advantage of this.

**Comment by pri-kise** [comment]
@louagej   Please check the following yammer post of @AndreiPanko .
https://www.yammer.com/dynamicsnavdev/threads/1762140027789312

> As source code of Shopify Connector is on GitHub we would like to reuse pattern we have for System App:
> 
> Prioritize submitting improvement over extensibility.
-  For example, if your customer needs to export multiple translations of a product to Shopify, instead of asking for making some objects extensible – submit PR that implements this feature.
- If extensibility is really necessary – for example to orchestrate multiple extensions dealing with various sales channels – please create PR directly. Remember to write the proper justification of scenario.
>
> We will not process extensibility requests for connector registered as Issues on GitHub.

I would also like it if they open up this app, but I'm not microsoft and I only try to help you to get this PR merged.

**Comment by onbuyuka** [comment]
Shopify Connector – Extensibility
As you know the Shopify Connector is made non-extensible. We plan to change it in the future, and we want to try a different model.

Motivation: we want to avoid misuse of extensibility to address bugs, minor improvements, or gaps – all of that end-user expects to be part of product. Millions of events spread across the code reduce readability and scalability, increase maintenance and upgrade costs for all parties.

As source code of Shopify Connector is on GitHub we would like to reuse pattern we have for System App:

Prioritize submitting improvement over extensibility. For example, if your customer needs to export multiple translations of a product to Shopify, instead of asking for making some objects extensible – submit PR that implements this feature.
If extensibility is really necessary – for example to orchestrate multiple extensions dealing with various sales channels – please create PR directly. Remember to write the proper justification of scenario.
We will not process extensibility requests for connector registered as Issues on GitHub.

**Pull request closed without merging**
