### PR TITLE
Add missing tests in Translation module

### PR DESCRIPTION
**Pull request by adrogin**
Add missing test cases in the Translation module.

### CODE REVIEW

**Comment by JesperSchulz** [comment]
Wow! Thanks! Love how you fix test holes in one of the application platform modules. This can only benefit the quality of the product. Very much appreciated! Thanks 😊
We're currently adding a CI process to this repository and would love to use this PR as a "guineapig" for that. I hence won't approve and merge this PR right away, but will keep it open a short while. Hope that is ok!

**Comment by adrogin** [comment]
Perfect! Sure, it's very good for me. Cool to be the first to test the new CI. :-)

**Review by JesperSchulz — APPROVED** [review]

**Comment by JesperSchulz** [comment]
CI/CD passed in our internal build system :-) The one here on GitHub needs a bit more love, before it will pass too. Merging PR!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47021.

**Pull request merged**
