### PR TITLE
Use Amount-Rounding in PriceAmount element

### LINKED ISSUE #13768: Rounding precision in DK/OIOUBL
In the PriceAmount element the rounding precision should adhere to the Unit-Amount rounding precision and not the Amount rounding precision (which is the default).

E.g. we an Invoice in DKK - amount is rounded to 2 decimals, and unit price is rounded to 4 decimals. The invoice line is

Quantity 360.00; Unit Price 3.515; Line Amount 1,265.40. 

However, when the Invoice is created, the Unit Price in the PriceAmount is rounded to 2 decimals. Thus the XML generated becomes

Quantity 360.00; Unit Price 3.52; Line Amount 1,265.40

The validation of the OIOUBL document fails because 360 * 3.52 <> 1,265.40

The XML generated:

```  <cac:InvoiceLine>
    <cbc:ID>30000</cbc:ID>
    <cbc:InvoicedQuantity unitCode="MTR">360.00</cbc:InvoicedQuantity>
    <cbc:LineExtensionAmount currencyID="DKK">1265.40</cbc:LineExtensionAmount>
    <cbc:AccountingCost></cbc:AccountingCost>
    <cac:OrderLineReference>
      <cbc:LineID>30000</cbc:LineID>
      <cac:OrderReference>
        <cbc:ID>AW</cbc:ID>
      </cac:OrderReference>
    </cac:OrderLineReference>
    <cac:AllowanceCharge>
      <cbc:ID>1</cbc:ID>
      <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
      <cbc:AllowanceChargeReason>Rabat</cbc:AllowanceChargeReason>
      <cbc:MultiplierFactorNumeric>1.000</cbc:MultiplierFactorNumeric>
      <cbc:SequenceNumeric>1</cbc:SequenceNumeric>
      <cbc:Amount currencyID="DKK">2154.60</cbc:Amount>
      <cbc:BaseAmount currencyID="DKK">2154.60</cbc:BaseAmount>
      <cac:TaxCategory>
        <cbc:ID schemeID="urn:oioubl:id:taxcategoryid-1.1" schemeAgencyID="320">ReverseCharge</cbc:ID>
        <cbc:Percent>63.00</cbc:Percent>
        <cac:TaxScheme>
          <cbc:ID schemeID="urn:oioubl:id:taxschemeid-1.1">63</cbc:ID>
          <cbc:Name>Moms</cbc:Name>
        </cac:TaxScheme>
      </cac:TaxCategory>
    </cac:AllowanceCharge>
    <cac:TaxTotal>
      <cbc:TaxAmount currencyID="DKK">316.35</cbc:TaxAmount>
      <cac:TaxSubtotal>
        <cbc:TaxableAmount currencyID="DKK">1265.40</cbc:TaxableAmount>
        <cbc:TaxAmount currencyID="DKK">316.35</cbc:TaxAmount>
        <cac:TaxCategory>
          <cbc:ID schemeID="urn:oioubl:id:taxcategoryid-1.1" schemeAgencyID="320">StandardRated</cbc:ID>
          <cbc:Percent>25.00</cbc:Percent>
          <cac:TaxScheme>
            <cbc:ID schemeID="urn:oioubl:id:taxschemeid-1.1">63</cbc:ID>
            <cbc:Name>Moms</cbc:Name>
          </cac:TaxScheme>
        </cac:TaxCategory>
      </cac:TaxSubtotal>
    </cac:TaxTotal>
    <cac:Item>
      <cbc:Description>****************</cbc:Description>
      <cbc:Name>*****************</cbc:Name>
      <cac:SellersItemIdentification>
        <cbc:ID schemeID="n/a">NNNNNNNNNN</cbc:ID>
      </cac:SellersItemIdentification>
    </cac:Item>
    <cac:Price>
      <cbc:PriceAmount currencyID="DKK">3.52</cbc:PriceAmount>
      <cbc:BaseQuantity unitCode="MTR">1</cbc:BaseQuantity>
    </cac:Price>
  </cac:InvoiceLine>
  ```

The expected XML :

```  <cac:InvoiceLine>
    <cbc:ID>30000</cbc:ID>
    <cbc:InvoicedQuantity unitCode="MTR">360.00</cbc:InvoicedQuantity>
    <cbc:LineExtensionAmount currencyID="DKK">1265.40</cbc:LineExtensionAmount>
    <cbc:AccountingCost></cbc:AccountingCost>
    <cac:OrderLineReference>
      <cbc:LineID>30000</cbc:LineID>
      <cac:OrderReference>
        <cbc:ID>AW</cbc:ID>
      </cac:OrderReference>
    </cac:OrderLineReference>
    <cac:AllowanceCharge>
      <cbc:ID>1</cbc:ID>
      <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
      <cbc:AllowanceChargeReason>Rabat</cbc:AllowanceChargeReason>
      <cbc:MultiplierFactorNumeric>1.000</cbc:MultiplierFactorNumeric>
      <cbc:SequenceNumeric>1</cbc:SequenceNumeric>
      <cbc:Amount currencyID="DKK">2154.60</cbc:Amount>
      <cbc:BaseAmount currencyID="DKK">2154.60</cbc:BaseAmount>
      <cac:TaxCategory>
        <cbc:ID schemeID="urn:oioubl:id:taxcategoryid-1.1" schemeAgencyID="320">ReverseCharge</cbc:ID>
        <cbc:Percent>63.00</cbc:Percent>
        <cac:TaxScheme>
          <cbc:ID schemeID="urn:oioubl:id:taxschemeid-1.1">63</cbc:ID>
          <cbc:Name>Moms</cbc:Name>
        </cac:TaxScheme>
      </cac:TaxCategory>
    </cac:AllowanceCharge>
    <cac:TaxTotal>
      <cbc:TaxAmount currencyID="DKK">316.35</cbc:TaxAmount>
      <cac:TaxSubtotal>
        <cbc:TaxableAmount currencyID="DKK">1265.40</cbc:TaxableAmount>
        <cbc:TaxAmount currencyID="DKK">316.35</cbc:TaxAmount>
        <cac:TaxCategory>
          <cbc:ID schemeID="urn:oioubl:id:taxcategoryid-1.1" schemeAgencyID="320">StandardRated</cbc:ID>
          <cbc:Percent>25.00</cbc:Percent>
          <cac:TaxScheme>
            <cbc:ID schemeID="urn:oioubl:id:taxschemeid-1.1">63</cbc:ID>
            <cbc:Name>Moms</cbc:Name>
          </cac:TaxScheme>
        </cac:TaxCategory>
      </cac:TaxSubtotal>
    </cac:TaxTotal>
    <cac:Item>
      <cbc:Description>****************</cbc:Description>
      <cbc:Name>*****************</cbc:Name>
      <cac:SellersItemIdentification>
        <cbc:ID schemeID="n/a">NNNNNNNNNN</cbc:ID>
      </cac:SellersItemIdentification>
    </cac:Item>
    <cac:Price>
      <cbc:PriceAmount currencyID="DKK">3.515</cbc:PriceAmount>
      <cbc:BaseQuantity unitCode="MTR">1</cbc:BaseQuantity>
    </cac:Price>
  </cac:InvoiceLine>
  ```

### PR DESCRIPTION
**Pull request by mortenseifert**
Fix #13768

### CODE REVIEW

**Comment by mortenseifert** [comment]
@PredragMaricic  any changes we can get this into next release? The customer now has several documents a month and we need to edit the xml file manually in order for it to pass validation.
Thx!

**Comment by PaulIvan** [comment]
@mortenseifert can you add a test that shows that a change in "Unit-Amount Rounding Precision" will in fact reflect in the exported file ?

**Comment by PaulIvan** [comment]
@mortenseifert also this change brakes some of the existing tests. could you run the test extension and fix those?

- AmountPriceDiscountOnServiceInvoiceWithLineInvoiceDiscount
- AmountPriceDiscountOnServiceInvoicePricesInclVATWithLineInvoiceDiscount
- AmountPriceDiscountOnServiceCrMemoWithLineInvoiceDiscount 
- AmountPriceDiscountOnServiceCrMemoPricesInclVATWithLineInvoiceDiscount 
- AmountPriceDiscountOnSalesInvoiceWithLineInvoiceDiscount
- AmountPriceDiscountOnSalesCrMemoWithLineInvoiceDiscount
- AmountPriceDiscountOnSalesInvoicePricesInclVATWithLineInvoiceDiscount
- AmountPriceDiscountOnSalesCrMemoPricesInclVATWithLineInvoiceDiscount

**Comment by mortenseifert** [comment]
I saw the test app included already two tests for more than two decimals. Just the tests did not test any data (other than the posting date). I have added code to the two functions.

@PaulIvan, the problem is really in the test case. When comparing the XML the text from the xml is compared with the formatted version (format with two decimal places). The compare should be the other way around (as it is in other test cases), where the xml text is evaluated to a decimal and the decimal is compared with the values from the document line.
```
    local procedure FormatAmount(Amount: Decimal): Text
    var
        TypeHelper: Codeunit "Type Helper";
    begin
        exit(Format(Amount, 0, TypeHelper.GetXMLAmountFormatWithTwoDecimalPlaces()))
    end;
```

**Comment by mortenseifert** [comment]
@PaulIvan I have added the code required to run the tests. Unfortunately I cannot get my environment setup to build and run the tests, I hope you can help with that.

**Comment by PaulIvan** [comment]
@mortenseifert We will accept this. I have made some minor changes when merging into our internal system.
It will most likely be released with the 19.1 version. so you should see it reflected on github next month

**Review by JesperSchulz — APPROVED** [review]
Some changes needed, but those will be part of the 19.1 push to GitHub.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.

**Pull request merged**
