### PR TITLE
Fix Sustainability preview posting subscriber

### LINKED ISSUE #27706: [Bug]: Sustainability subscribers broke a preview posting
### Describe the issue

Hello,
We have the next error on document preview posting.
Error message: 
The binding of codeunit 6228 was unsuccessful. The codeunit has already been bound.

AL call stack: 
"Sust. Purchase Subscriber"(CodeUnit 6225).OnAfterBindSubscription line 3 - Sustainability by Microsoft
"Gen. Jnl.-Post Preview"(CodeUnit 19).OnAfterBindSubscription(Event) line 2 - Base Application by Microsoft
"Gen. Jnl.-Post Preview"(CodeUnit 19).PreviewStart line 16 - Base Application by Microsoft
"Gen. Jnl.-Post Preview"(CodeUnit 19).Preview line 7 - Base Application by Microsoft

The issue related to extension Sustainability. This app added some tables to preview but it was not implemented correctly. When some error occurs in the preview posting the manual subscription codeunit stays already bound. So on the next run of preview posting, this error occurs.
I suggest fixing it and make like in codeunit 6496 "Serv. Posting Preview Binding" from the Base Application.

Basically, we need to use bindSubscription inside a if then and add a clear temporary record from the previous possible run.

### Expected behavior

There is no error on the preview posting related to the already bounded codeunit 6228 

### Steps to reproduce

1. Prepare a document that will cause a posting error.
2. Run Preview posting.
3. Run preview posting again

### Additional context

_No response_

### I will provide a fix for a bug

- [x] I will provide a fix for a bug

### PR DESCRIPTION
**Pull request by vlkov**
#### Summary 
 Change the binding preview posting codeunits using try method like in service posting
#### Work Item(s) 
Fixes #27706

Fixes [AB#559882](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559882)

### CODE REVIEW

**Review by JesperSchulz — APPROVED** [review]

**Comment by JesperSchulz** [comment]
This PR was processed internally. Unsure why tests are failing here on GitHub. We will need to investigate.

**Comment by JesperSchulz** [comment]
Fix was backported for release with 25.3 as well.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 27886.

**Comment by JesperSchulz** [comment]
@vlkov, could you try to pull from main? Then we'll give it another run. It should pass then!

**Comment by vlkov** [comment]
@JesperSchulz merged from main

**Comment by JesperSchulz** [comment]
> @JesperSchulz merged from main

Let's run once more. Would love to merge this PR here on GitHub rather than to close it 😊

**Review by JesperSchulz — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Sorry @vlkov, could you try to pull from main one last time? If this doesn't work, I'll force merge your PR. I just really would love our CI to come back to life!

**Comment by JesperSchulz** [comment]
We'll force merge now 😊

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27743.

**Pull request merged**
