### PR TITLE
Add Events to DataSearch

### PR DESCRIPTION
**Pull request by pri-kise**
With this pull Request, I want to provide more extensibility for the Data Search App, that we can use this app for our specific tables with subtypes, too.

### CODE REVIEW

**Comment by BardurKnudsen** [comment]
Thanks for suggesting this. We have created an internal work item ('bug') and will implement this one way or another.
Stay tuned!

**Comment by pri-kise** [comment]
@BardurKnudsen could you please keep me updated on this PR as soon as you update this functionality

**Comment by pri-kise** [comment]
@JesperSchulz it is not ideal how PullRequest and issues are getting moderated on this repository.
The last time i created an issue for such small pieces on this repo.
Then the suggestion, was to create a pull Request.
Now it's the other way round and shouldn't have taken my time to create this pullrequest. --- this can very frustrating.

**Comment by JesperSchulz** [comment]
Did you create an issue for this request before? And there we requested you to create a PR? That's unfortunate, as this feature is brand new, and you aren't the only one having extensibility requests. Rather than accepting a handful of individual extensibility requests, Bardur has concluded to take all of them into consideration and to address them in one, unified way.

The suggested approach is to start with an issue, and if we agree it's a good issue to address, you can create a PR. In the BaseApp pilot, we're trying to enforce that. Getting a PR closed is indeed a frustrating experience, which we try to avoid. Here that didn't seem to work 🙄 Sorry about that. I'll see how we can improve in this repo!

However, I did speak to Bardur and he is of course taking your PR into consideration. It DOES still have value, as it clearly documents the extensibility points, you need. So it wasn't all a waste!

**Comment by BardurKnudsen** [comment]
@pri-kise We have created this separate codeunit in the Data Search app, which contains a set of integration events.

codeunit 2682 "Data Search Events"
{
    SingleInstance = true;

    /// <summary>
    /// Specifies the Field No. for the table type field. For example "Sales Header" would specify 1 = "Document Type"
    /// </summary>
    /// <param name="TableNo">The table no. of the table that is being searched.</param>
    /// <param name="FieldNo">The field no. of the 'document type' field.</param>
    [IntegrationEvent(false, false)]
    procedure OnGetFieldNoForTableType(TableNo: Integer; var FieldNo: Integer)
    begin
    end;

    /// <summary>
    /// Specifies the parent table if a table is a sub-table in a header/lines construct, such as Sales Line
    /// </summary>
    /// <param name="SubTableNo">The table no. of the table that is being searched.</param>
    /// <param name="ParentTableNo">If the the table is a sub-table, please specify the parent table here</param>
    [IntegrationEvent(false, false)]
    procedure OnGetParentTable(SubTableNo: Integer; var ParentTableNo: Integer)
    begin
    end;

    /// <summary>
    /// Specifies the list page no. to be used for displaying the record. 
    /// Only needed if the page is not the standard list/card page for the table
    /// </summary>
    /// <param name="TableNo">The table no. of the table that is being displayed.</param>
    /// <param name="TableType">If the table as a 'Document Type'-like field, this value specifies the type as integer.</param>
    /// <param name="PageNo">The page to use to display the record.</param>
    [IntegrationEvent(false, false)]
    procedure OnGetListPageNo(TableNo: Integer; TableType: Integer; var PageNo: Integer)
    begin
    end;

    /// <summary>
    /// Specifies the card page no. to be used for displaying the record. If no card exists, then specify the list page no.
    /// Only needed if the page is not the standard list/card page for the table
    /// </summary>
    /// <param name="TableNo">The table no. of the table that is being displayed.</param>
    /// <param name="TableType">If the table as a 'Document Type'-like field, this value specifies the type as integer.</param>
    /// <param name="PageNo">The page to use to display the record.</param>
    [IntegrationEvent(false, false)]
    procedure OnGetCardPageNo(TableNo: Integer; TableType: Integer; var PageNo: Integer)
    begin
    end;

    /// <summary>
    /// Specifies the header RecordRef to a corresponding line RecordRef for e.g. sales line -> sales header
    /// </summary>
    /// <param name="LineRecRef">The line record</param>
    /// <param name="HeaderRecRef">The parent of the line record</param>
    [IntegrationEvent(false, false)]
    procedure OnMapLineRecToHeaderRec(var LineRecRef: RecordRef; var HeaderRecRef: RecordRef)
    begin
    end;

    /// <summary>
    /// Enables adding and removing tables from the default initial setup for tables to search.
    /// </summary>
    /// <param name="ProfileID">Page ID for the selected role center</param>
    /// <param name="ListOfTableNumbers">List of integer. Already filled with standard tables.</param>
    [IntegrationEvent(false, false)]
    procedure OnAfterGetRolecCenterTableList(RoleCenterID: Integer; var ListOfTableNumbers: List of [Integer])
    begin
    end;

    /// <summary>
    /// Specifies whether a field is excluded from the default fields in a table, based on its table relation.
    /// Typically we would exclude fields from search that have relations to posting groups, reason codes, etc.
    /// </summary>
    /// <param name="RelatedTableNo">The table no. that the field has relation to.</param>
    /// <param name="IsExcluded">true/false whether the field should be excluded from the default setup.</param>
    [IntegrationEvent(false, false)]
    procedure OnGetExcludedRelatedTableField(RelatedTableNo: Integer; var IsExcluded: Boolean)
    begin
    end;
}

And a test-example that you would add to your solution:

codeunit 139508 "Test Data Search On Archives"
{
    EventSubscriberInstance = Manual;
    
    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Data Search Events", 'OnGetFieldNoForTableType', '', true, true)]
    local procedure OnGetFieldNoForTableType(TableNo: Integer; var FieldNo: Integer)
    begin
        case TableNo of
            Database::"Sales Header Archive", Database::"Sales Line Archive":
                FieldNo := 1;
        end;
    end;

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Data Search Events", 'OnGetParentTable', '', true, true)]
    local procedure OnGetParentTable(SubTableNo: Integer; var ParentTableNo: Integer)
    begin
        case SubTableNo of
            Database::"Sales Line Archive":
                ParentTableNo := Database::"Sales Header Archive";
        end;
    end;

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Data Search Events", 'OnGetListPageNo', '', true, true)]
    local procedure OnGetListPageNo(TableNo: Integer; TableType: Integer; var PageNo: Integer)
    var
        SalesDocumentType: Enum "Sales Document Type";
    begin
        case TableNo of
            Database::"Sales Header Archive":
                case TableType of
                    SalesDocumentType::Order.AsInteger():
                        PageNo := Page::"Sales Order Archives";
                    SalesDocumentType::"Blanket Order".AsInteger():
                        PageNo := Page::"Blanket Sales Order Archives";
                    SalesDocumentType::Quote.AsInteger():
                        PageNo := Page::"Sales Quote Archives";
                    else
                        PageNo := Page::"Sales List Archive";
                end;
        end;
    end;

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Data Search Events", 'OnGetCardPageNo', '', true, true)]
    local procedure OnGetCardPageNo(TableNo: Integer; TableType: Integer; var PageNo: Integer)
    var
        SalesDocumentType: Enum "Sales Document Type";
    begin
        case TableNo of
            Database::"Sales Header Archive":
                case TableType of
                    SalesDocumentType::Order.AsInteger():
                        PageNo := Page::"Sales Order Archive";
                    SalesDocumentType::"Blanket Order".AsInteger():
                        PageNo := Page::"Blanket Sales Order Archive";
                    SalesDocumentType::Quote.AsInteger():
                        PageNo := Page::"Sales Quote Archive";
                end;
        end;
    end;

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Data Search Events", 'OnMapLineRecToHeaderRec', '', true, true)]
    local procedure OnMapLineRecToHeaderRec(var LineRecRef: RecordRef; var HeaderRecRef: RecordRef)
    var
        SalesHeaderArchive: Record "Sales Header Archive";
        SalesLineArchive: Record "Sales Line Archive";
    begin
        if LineRecRef.Number <> Database::"Sales Line Archive" then
            exit;
        LineRecRef.SetTable(SalesLineArchive);
        SalesHeaderArchive.Get(SalesLineArchive."Document Type", SalesLineArchive."Document No.", SalesLineArchive."Doc. No. Occurrence", SalesLineArchive."Version No.");
        HeaderRecRef.GetTable(SalesHeaderArchive);
    end;

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Data Search Events", 'OnAfterGetRolecCenterTableList', '', true, true)]
    local procedure OnAfterGetRolecCenterTableList(RoleCenterID: Integer; var ListOfTableNumbers: List of [Integer])
    begin
        if not ListOfTableNumbers.Contains(Database::"Sales Header Archive") then
            ListOfTableNumbers.Add(Database::"Sales Header Archive");
        if not ListOfTableNumbers.Contains(Database::"Sales Line Archive") then
            ListOfTableNumbers.Add(Database::"Sales Line Archive");
    end;

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Data Search Events", 'OnGetExcludedRelatedTableField', '', true, true)]
    local procedure OnGetExcludedRelatedTableField(RelatedTableNo: Integer; var IsExcluded: Boolean)
    begin
        IsExcluded := IsExcluded or (RelatedTableNo in [Database::"Customer Price Group", Database::"Work Type", Database::"Transport Method"]);
    end;
}

**Comment by pri-kise** [comment]
@BardurKnudsen  I haven't checked the preview, but shouldn't these events be internal?
Otherwise - lgtm.

**Pull request closed without merging**
