### PR TITLE
[E-Document Connector] SignUp E-Document Connector

### LINKED ISSUE #27054: [BC Idea]: Enable connector with SignUp for E-Documents
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=b72f1e69-7535-ef11-8409-6045bddca9de

### Description

It will be good to have connector with SignUp service in E-Documents framework, so it will offer more electronic invoicing services as a choice for users.

### I will provide the implementation for this BC Idea

- [X] I will provide the implementation for this BC Idea

### PR DESCRIPTION
**Pull request by geschwint**
#### Summary
E-Documents connector interface implementation between Business Central and SignUp Web API for electronic invoices

#### Work Item(s) 
Fixes #27054 

Fixes [AB#541805](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/541805)

### CODE REVIEW

**Comment by geschwint** [comment]
Not much will change now. Essentially done. I'll have this as Draft at the moment as I might do really minor adjustments in certain cases.

**Comment by geschwint** [comment]
Be advised that this pull request depends on the completion of pull request #27051 as I am using new fields from table Customer

**Comment by geschwint** [comment]
@aholstrup1 I wonder if something went wrong. I noticed your force-push of changes into main, thus I pulled the changes into my fork and accepted all incoming changes. Then I merged into my branch and pushed to get in sync. Still indication of 107 files changed and we only changed/added files below EDocumentsConnector folder. Asking for advice

**Comment by plakna** [comment]
Hi @geschwint, I had the same issue as you. I synced my fork, cherry-picked my commits, and then created a new PR (to get rid of the unwanted commits in the PR).

A cherry-pick or rebase is necessary, i guess. If you merge, you'll bring the altered commits back (since the forced git push wasn’t executed on your side).

There might be a better way, but this approach worked for me in the end.

**Comment by geschwint** [comment]
Hi @plakna Sounds reasonable. I will do that.

CC @aholstrup1

**Comment by geschwint** [comment]
@aholstrup1 This pull request has been replaced by #27261 

Due to using merge and not rebase.

**Pull request closed without merging**
