### PR TITLE
Check for Field Length on setting via UI

### LINKED ISSUE #1239: [Event Change] Table 81 - OnBeforeLookUpAppliesToDocCust
The publisher should contain a "Handled"-Flag and the record should be passed as VAR

image

image

Same for publisher
- OnBeforeLookUpAppliesToDocEmpl
- OnBeforeLookUpAppliesToDocVend

### PR DESCRIPTION
**Pull request by pri-kise**
Fixes  [#12381](https://github.com/microsoft/ALAppExtensions/issues/12381)
Currently the length check is optional an only performed via UI

### CODE REVIEW

**Comment by pri-kise** [comment]
Maybe @JesperSchulz you can take a look at this PR, since we had the communication on this old issue.

**Comment by JesperSchulz** [comment]
I'll take a look!

**Review by JesperSchulz — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Releases with 23.0 🥳

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12071.

**Pull request merged**
