### PR TITLE
Changed ABS Container API Directory Identification

### PR DESCRIPTION
**Pull request by JulianTillmann**
Fix for Issue #19756 

Directories were not properly identified

### CODE REVIEW

**Comment by mazhelez** [comment]
Great :) The fix looks good enough!

Is there a way to write a test that would fail with the previous version, but succeeds with your changes?

**Comment by JulianTillmann** [comment]
@mazhelez 
I don't know, if you have multiple folders in a test azure container or a mock you could maybe create a scenario.

**Comment by mazhelez** [comment]
> @mazhelez I don't know, if you have multiple folders in a test azure container or a mock you could maybe create a scenario.

Hey, I'm not sure I understand the question...?

In any case, for automated tests (although they do not run automatically in the gates), we use [azurite](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio) and it should be possible to 
 write a test that creates blob in folders and subfolders and then retrieves them with the correct type and everything.

**Comment by JulianTillmann** [comment]
ok, feel free to do it with azurite or any other way :-)

**Comment by mazhelez** [comment]
> ok, feel free to do it with azurite or any other way :-)

@JulianTillmann the idea is that you (as a contributor) add the test 🦸

**Comment by JulianTillmann** [comment]
> > ok, feel free to do it with azurite or any other way :-)
> 
> @JulianTillmann the idea is that you (as a contributor) add the test 🦸

I have enough on my plate already, I will not have the time to 

and since there has not been any tests for this before or the bug would have been noticed, this does not seem to be a priority

**Comment by mazhelez** [comment]
Hey @JulianTillmann 

I did some testing (with azurite) and here are the results:
I used the following hierarchy:
```
|   rootblob1
|   rootblob2
|
\---folder1
    |   folderblob1
    |   folderblob2
    |
    +---subfolder1
    |   |   subfolderblob1
    |   |   subfolderblob2
    |   |
    |   \---subsubfolder
    |           subsubfolderfolderblob1
    |           subsubfolderfolderblob2
    |
    \---subfolder2
        \---subsubfolder
                subsubfolderfolderblob1
                subsubfolderfolderblob2
```
and created a sample explorer page.

Currently, this is how it looks (let's agree that is bit messy):
image


Applying you changes, it looks like the following image: only BLOBs in the result, `IsDirectory` doesn't seem to work.
image

I added some changes as well (haven't pushed them yet) and with my changes it looks like this:
image

Let me know what you think. It's a quite interesting case. Maybe @SimonOfHH can share an opinion as well.

**Comment by SimonOfHH** [comment]
> It's a quite interesting case. Maybe @SimonOfHH can share an opinion as well.

I also had this problem in one of my early implementations of this and was unsatisfied with the result 😅 Your result looks good to me @mazhelez and the fix looks also simple enough.
I wonder how one would structure a test for this, though 🤔

**Comment by JulianTillmann** [comment]
@mazhelez 
I'm pretty sure that my IsDirectory function worked but I cannot see what you changed, so I'm happy to go with your solution :-)

**Comment by mazhelez** [comment]
@JulianTillmann just created a PR to your branch with my additions: https://github.com/JulianTillmann/ALAppExtensions/pull/1

If you approve with the changes, just merge it and I'll continue with the uptake.

**Comment by JulianTillmann** [comment]
looks good

**Review by mazhelez — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47660.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 47679.

**Comment by JulianTillmann** [comment]
> Availability update: We will publish a fix for this issue in the next update for release 21.
> 
> Build ID to track: 47679.

so this fix will not be applied to BC20?

**Comment by JulianTillmann** [comment]
@mazhelez @JesperSchulz 
unfortunately this doesn't work in BC20 CU1. 

image

image

we also need a fix for BC20 as well

**Comment by JulianTillmann** [comment]
> Issues addressed on GitHub will only get implemented in the latest released version - in this case 21.x. If we had to backport to all supported versions, it would be too time consuming.

so I would need to create a support case to get a fix for BC20? 

and it's not fixed for BC21 as I wrote 27 days ago

**Comment by JesperSchulz** [comment]
To me it looks like this is fixed from 21.1 and newer? Try looking again - it really should be fixed. You can even see the changes here in the repo.
If you really need this for 20.x, I can backport the change for you as an exception. But usually, you should not expect changes coming in through GitHub to be backported. If you've got bugs of that nature, support cases would indeed be the way to go.
I'll do the backport to 20.x right away.

**Comment by JulianTillmann** [comment]
> To me it looks like this is fixed from 21.1 and newer? Try looking again - it really should be fixed. You can even see the changes here in the repo. 

I just tried again with BC21 CU2. The content-type is "application/octet-stream" instead of "directory" or "Directory" 

image

**Comment by JesperSchulz** [comment]
So this doesn't even work in 21.2? That's bad news. We need a new PR here on GitHub for that, as my team unfortunately doesn't have capacity to fix bugs in open source PRs.

**Comment by mazhelez** [comment]
@JulianTillmann is there another issue other than the content type?

It's a weird one as there is a test that tests the content type for directories 🤔

**Comment by mazhelez** [comment]
@JulianTillmann I did some testing on our side and I cannot repro the issue you experience.

image

This time I tested against an actual _Azure Blob Storage_ account (typically we run tests using azurite).
I tested with BLOBs created with `PutBlobBlockBlobText`. E.g.:
```
  BlobName := 'Folder1/Subfolder1/' + Format(CreateGuid());
  if ABSBlobClient.PutBlobBlockBlobText(BlobName, BlobName).IsSuccessful() then
      Message('Blob %1 created successfully', BlobName);
```

I also tested manually creating BLOBs from the Azure portal:
image

This is how it looks in the portal:
image

And this is how this looks in BC:
image


How are your BLOBs created? Can you at least try provide repro steps? Otherwise, there is very little we can do.

**Comment by JulianTillmann** [comment]
@mazhelez 
that's extremely strange

I mostly created the folders manually in azure portal:
image

but I now also tried PutBlobBlockBlobText() and Upload a file from azure portal into a specific folder like you showed. but then the content-type is just empty for me:
image

I'm not sure on how to provide a better repro :-(  could we maybe do a teams session somehow sometime?

**Comment by mazhelez** [comment]
That's indeed very weird 🤔 

I can't even see the "Add Directory" action on my container (and I am the owner of the subscription, so I should have god powers).

I just tried adding folders using the _Azure Storage Explorer_ and the result is as expected: the content type is "Directory" for all the folders.

The only thing that's different is that I'm running the latest version of the ABS module in _System Application_. I don't think anything has changes since the fix for the hierarchy, but I might be wrong. Any chance you can run the latest version?

Otherwise, I'd gladly help out with a Teams session, where I can let you test with my ABS and vice versa.

**Pull request merged**
