### PR TITLE
Headers.GetValue shielding

### PR DESCRIPTION
**Pull request by PaulFurlet**
Suggestion to add checking Headers containing certain keys based on issue #22132

### CODE REVIEW

**Comment by PaulFurlet** [comment]
@microsoft-github-policy-service agree

**Comment by pri-kise** [comment]
@aholstrup1 you recently updated the AL-GO for this repo?
May you help with the Build Process, that isn't working here?

**Review by darjoo — APPROVED** [review]

**Comment by aholstrup1** [comment]
As @pri-kise pointed out, this is indeed due to the latest updates to the AL-GO files. I've updated the files with a fix. @PaulFurlet can I get you to push another change to your branch to trigger a new build? E.g. pull the latest changes from main. 
Sorry for the inconvenience

**Comment by PaulFurlet** [comment]
> As @pri-kise pointed out, this is indeed due to the latest updates to the AL-GO files. I've updated the files with a fix. @PaulFurlet can I get you to push another change to your branch to trigger a new build? E.g. pull the latest changes from main. Sorry for the inconvenience

It is ok.
I noticed one more missing potential place and added it.

**Comment by pri-kise** [comment]
I'm not sure when the Method `TryGetContentHeaders` will fail, but maybe this causes the ContentHeaders to be un-initialized.

    local procedure CreateSharedKeyStringToSign(HttpRequestMessage: HttpRequestMessage; StorageAccount: Text): Text
    var
        RequestHeaders, ContentHeaders : HttpHeaders;
        StringToSign: Text;
    begin
        HttpRequestMessage.GetHeaders(RequestHeaders);
//-> Maybe this is the cause of teh error
        if TryGetContentHeaders(HttpRequestMessage, ContentHeaders) then;
//->
        StringToSign += HttpRequestMessage.Method() + NewLine();
///-> ContentHeaders might be unitialized on this place
        StringToSign += GetHeaderValueOrEmpty(ContentHeaders, 'Content-Encoding') + NewLine();
        StringToSign += GetHeaderValueOrEmpty(ContentHeaders, 'Content-Language') + NewLine();
        StringToSign += GetHeaderValueOrEmpty(ContentHeaders, 'Content-Length') + NewLine();
        StringToSign += GetHeaderValueOrEmpty(ContentHeaders, 'Content-MD5') + NewLine();
        StringToSign += GetHeaderValueOrEmpty(ContentHeaders, 'Content-Type') + NewLine();
        StringToSign += GetHeaderValueOrEmpty(RequestHeaders, 'Date') + NewLine();
        StringToSign += GetHeaderValueOrEmpty(RequestHeaders, 'If-Modified-Since') + NewLine();
        StringToSign += GetHeaderValueOrEmpty(RequestHeaders, 'If-Match') + NewLine();
        StringToSign += GetHeaderValueOrEmpty(RequestHeaders, 'If-None-Match') + NewLine();
        StringToSign += GetHeaderValueOrEmpty(RequestHeaders, 'If-Unmodified-Since') + NewLine();
        StringToSign += GetHeaderValueOrEmpty(RequestHeaders, 'Range') + NewLine();
        StringToSign += GetCanonicalizedHeaders(RequestHeaders) + NewLine();
        StringToSign += GetCanonicalizedResource(StorageAccount, HttpRequestMessage.GetRequestUri());

        exit(StringToSign);
    end;

**Comment by PaulFurlet** [comment]
@darjoo I suppose, @pri-kise is right and my suggestion to fix that is to put part with ContentHeaders usage to conditional block just for this case. But I am not strong in this area, probably I do not see whole picture.
What will you say about it?
```al
    local procedure CreateSharedKeyStringToSign(HttpRequestMessage: HttpRequestMessage; StorageAccount: Text): Text
    var
        RequestHeaders, ContentHeaders : HttpHeaders;
        StringToSign: Text;
    begin
        HttpRequestMessage.GetHeaders(RequestHeaders);
        // if TryGetContentHeaders(HttpRequestMessage, ContentHeaders) then; // <-- shifted below
        StringToSign += HttpRequestMessage.Method() + NewLine();
        if TryGetContentHeaders(HttpRequestMessage, ContentHeaders) then begin // <-- here comes begin
            StringToSign += GetHeaderValueOrEmpty(ContentHeaders, 'Content-Encoding') + NewLine();
            StringToSign += GetHeaderValueOrEmpty(ContentHeaders, 'Content-Language') + NewLine();
            StringToSign += GetHeaderValueOrEmpty(ContentHeaders, 'Content-Length') + NewLine();
            StringToSign += GetHeaderValueOrEmpty(ContentHeaders, 'Content-MD5') + NewLine();
            StringToSign += GetHeaderValueOrEmpty(ContentHeaders, 'Content-Type') + NewLine();
        end; // <-- here comes end
        StringToSign += GetHeaderValueOrEmpty(RequestHeaders, 'Date') + NewLine();
        StringToSign += GetHeaderValueOrEmpty(RequestHeaders, 'If-Modified-Since') + NewLine();
        StringToSign += GetHeaderValueOrEmpty(RequestHeaders, 'If-Match') + NewLine();
        StringToSign += GetHeaderValueOrEmpty(RequestHeaders, 'If-None-Match') + NewLine();
        StringToSign += GetHeaderValueOrEmpty(RequestHeaders, 'If-Unmodified-Since') + NewLine();
        StringToSign += GetHeaderValueOrEmpty(RequestHeaders, 'Range') + NewLine();
        StringToSign += GetCanonicalizedHeaders(RequestHeaders) + NewLine();
        StringToSign += GetCanonicalizedResource(StorageAccount, HttpRequestMessage.GetRequestUri());

        exit(StringToSign);
    end;
```

**Comment by JesperSchulz** [comment]
@darjoo, could you follow up on this PR when 2023 Wave 1 has been sent off? Let's get this PR processed.

**Review by JesperSchulz — APPROVED** [review]

**Review by JesperSchulz — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Changes processed for 22.2!

**Comment by PaulFurlet** [comment]
@JesperSchulz great news!
Is this normal behavior for not passing checks?

All checks fail with the same error "The remote server returned an error: (410) Gone."

**Review by IhorHandziuk — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56517.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10737.

**Pull request merged**
