### PR TITLE
[E-Document Core] Added field Service Participant Id to Vendor and Customer

### LINKED ISSUE #27060: [BC Idea]: Customer and Vendor field to save identification data related to E-Document Service. Used in E-Document connectors
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=6f826ec2-eb5a-ef11-a4e5-000d3ae30703#

### Description

Customer and Vendor needs a field to save identification data related to E-Document Service. Used in E-Document connectors

### I will provide the implementation for this BC Idea

- [X] I will provide the implementation for this BC Idea

### PR DESCRIPTION
**Pull request by geschwint**
Customer and Vendor needs a field to save identification data related to E-Document Service. Used in E-Document connectors

Fixes #27060 

Fixes [AB#544798](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544798)

### CODE REVIEW

**Comment by geschwint** [comment]
@aholstrup1 This pull request has replaced #27051 due to using merge instead of rebase policy. Thank you for your patience

**Comment by Groenbech96** [comment]
@geschwint What if customer is sending to multiple services?

**Comment by geschwint** [comment]
@Groenbech96 You are raising a valid question here. I'll raise this question in our channel

**Comment by geschwint** [comment]
Comment on last commit. Resolving object number conflict. Just allocated next available number. Error in build

**Comment by geschwint** [comment]
Closing this PR as MS is providing a solution in PR #27509

**Pull request closed without merging**
