### PR TITLE
:bug: Use correct Format to Show RecordId in Current Language

### PR DESCRIPTION
**Pull request by pri-kise**

### CODE REVIEW

**Comment by IhorHandziuk** [comment]
@pri-kise , is there a reason why Standard Display Format 2 is preferred over Standard Display Format 1 when showing the record ID as caption on the translation page?

**Comment by pri-kise** [comment]
See the documentation https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-recordid-method-record#remarks 
Format(RecordId, 0, 1) prints the RecordId in the current langauge

**Review by darjoo — APPROVED** [review]

**Comment by darjoo** [comment]
Processing it internally currently. Will merge once that is done.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.

**Pull request merged**
