### PR TITLE
Add new storage service API versions

### PR DESCRIPTION
**Pull request by Krajzys**
Add more values to Storage Service API Version enum.

### CODE REVIEW

**Comment by Krajzys** [comment]
@microsoft-github-policy-service agree company="IT.integro"

**Review by pri-kise — APPROVED** [review]

**Comment by Krajzys** [comment]
I'm not sure why the builds are failing, could someone help?

**Comment by pri-kise** [comment]
I have the same problem and @mazhelez mentions that this might be caused by AL-GO and that she will check this problem out.

**Comment by JesperSchulz** [comment]
PR locked. Processing internally in main branch.

**Review by JesperSchulz — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11007.

**Comment by JesperSchulz** [comment]
Releases with 22.3.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 57804.

**Pull request merged**
