### PR TITLE
Two new scenarios for GL entries and

### PR DESCRIPTION
**Pull request by Bertverbeek4PS**
Added two scenarios for BCPT:
- Posting Purchase Invoice
- Posting General Journal

@henrikfrovst

### CODE REVIEW

**Review by henrikfrovst — APPROVED** [review]

**Review by henrikfrovst — APPROVED** [review]

**Comment by ChethanT** [comment]
The following errors are thrown when the tests are built

...\Tests\BCPT-SampleTests\src\BCPTCPostPurchInv.Codeunit.al(52,9): error AA0021: Variable declarations should be ordered by type. Variables should be sorted like this: Record, Report, Codeunit, XmlPort, Page, Query, Notification, BigText, DateFormula, RecordId, RecordRef, FieldRef, and FilterPageBuilder. The rest of the variables are not sorted.
...\Tests\BCPT-SampleTests\src\BCPTCPostPurchInv.Codeunit.al(76,21): error AA0008: You must specify open and close parenthesis after 'SessionId'.
...\Tests\BCPT-SampleTests\src\BCPTPostGLEntries.Codeunit.al(131,24): error AA0008: You must specify open and close parenthesis after 'SessionId'.
...\Tests\BCPT-SampleTests\src\BCPTCPostPurchInv.Codeunit.al(108,9): error AA0008: You must specify open and close parenthesis after 'Init'.
...\Tests\BCPT-SampleTests\src\BCPTCPostPurchInv.Codeunit.al(116,38): error AA0008: You must specify open and close parenthesis after 'SelectRandomItem'.
...\Tests\BCPT-SampleTests\src\BCPTCPostPurchInv.Codeunit.al(106,9): error AA0137: Variable 'BCPTTestContext' is unused in 'CreatePurchaseLine'.
...\Tests\BCPT-SampleTests\src\BCPTCPostPurchInv.Codeunit.al(127,19): error AA0008: You must specify open and close parenthesis after 'SessionId'.

**Comment by Bertverbeek4PS** [comment]
> @Bertverbeek4PS The following errors are thrown when the tests are built
> 
> ...\Tests\BCPT-SampleTests\src\BCPTCPostPurchInv.Codeunit.al(52,9): error AA0021: Variable declarations should be ordered by type. Variables should be sorted like this: Record, Report, Codeunit, XmlPort, Page, Query, Notification, BigText, DateFormula, RecordId, RecordRef, FieldRef, and FilterPageBuilder. The rest of the variables are not sorted. ...\Tests\BCPT-SampleTests\src\BCPTCPostPurchInv.Codeunit.al(76,21): error AA0008: You must specify open and close parenthesis after 'SessionId'. ...\Tests\BCPT-SampleTests\src\BCPTPostGLEntries.Codeunit.al(131,24): error AA0008: You must specify open and close parenthesis after 'SessionId'. ...\Tests\BCPT-SampleTests\src\BCPTCPostPurchInv.Codeunit.al(108,9): error AA0008: You must specify open and close parenthesis after 'Init'. ...\Tests\BCPT-SampleTests\src\BCPTCPostPurchInv.Codeunit.al(116,38): error AA0008: You must specify open and close parenthesis after 'SelectRandomItem'. ...\Tests\BCPT-SampleTests\src\BCPTCPostPurchInv.Codeunit.al(106,9): error AA0137: Variable 'BCPTTestContext' is unused in 'CreatePurchaseLine'. ...\Tests\BCPT-SampleTests\src\BCPTCPostPurchInv.Codeunit.al(127,19): error AA0008: You must specify open and close parenthesis after 'SessionId'.

Sorry @ChethanT my codecop rules somehow are turned off. Have fixed the issues.
Sorry.

**Comment by ChethanT** [comment]
Changes have been merged and will be available in 23.0
@henrikfrovst, @JesperSchulz please approve and close the PR.

**Review by ChethanT — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10814.

**Pull request merged**
