### PR TITLE
[Shopify] Fix sync catalog price issue

### LINKED ISSUE #27535: [Bug]: Shopify Connector : Cannot sync catalog price from BC to Shopify for catalog larger than 100 products
### Describe the issue

When users try to synchronize prices through the action available on Shopify Catalogs page. Only the 100 first prices are synchronized. So if the Shopify Catalog contains more than 100 product, only 100 of them will be updated.

This problem results from a difference between two GraphQL requests made during this process: 

> **1) codeunit 30296 "Shpfy GQL CatalogPrices"**
> '{"query": "query { catalog(id: \"gid://shopify/Catalog/{{CatalogId}}\") { id priceList {id currency prices(first:100) {edges {cursor node {variant {id product {id}} price {amount} compareAtPrice {amount}}} pageInfo {hasNextPage}}}}}"}'
> 
> **2) codeunit 30297 "Shpfy GQL NextCatalogPrices"**
> '{"query": "query { catalog(id: \"gid://shopify/Catalog/{{CatalogId}}\") { id priceList {id prices(first:100, after:\"{{After}}\") {edges {cursor node {variant {id} price {amount} compareAtPrice {amount}}} pageInfo {hasNextPage}}}}}"}'

Some necessary nodes are missing in NextCatalogPrices. Here is a fixed request : 

> '{"query": "query { catalog(id: \"gid://shopify/Catalog/{{CatalogId}}\") { id priceList {id **_currency_** prices(first:100, after:\"{{After}}\") {edges {cursor node {variant {id **_product {id}_**} price {amount} compareAtPrice {amount}}} pageInfo {hasNextPage}}}}}"}'

Indeed, the lack of node variant.product.id node in Shopify's response does not allow the connector to work properly, since this json node is used in the codeunit 30290 "Shpfy Catalog API"

Image

### Expected behavior

Being able to sync prices for catalogs with more than 100 products. 

### Steps to reproduce

1. Setup Shopify connector to sync catalogs
2. Go to page Shpfy Catalogs (30159, List)
3. Use action Get Catalog
4. Check Sync Prices on a record related to a Shopify Catalog with more than 100 products / prices
5. Use action Sync Prices

### Additional context

Issue found in version 24.5.23489.24156 and 25.0.23364.25445 of Shopify Connector
It would be great if a patch could be released for Business Central Saas 24.5.

### I will provide a fix for a bug

- [x] I will provide a fix for a bug

### PR DESCRIPTION
**Pull request by glachana**
#### Summary 
When users try to synchronize prices through the action available on Shopify Catalogs page. Only the 100 first prices are synchronized. So if the Shopify Catalog contains more than 100 product, only 100 of them will be updated.

This problem results from a difference between two GraphQL requests made during this process:

1) codeunit 30296 "Shpfy GQL CatalogPrices"
'{"query": "query { catalog(id: "gid://shopify/Catalog/{{CatalogId}}") { id priceList {id currency prices(first:100) {edges {cursor node {variant {id product {id}} price {amount} compareAtPrice {amount}}} pageInfo {hasNextPage}}}}}"}'

2) codeunit 30297 "Shpfy GQL NextCatalogPrices"
'{"query": "query { catalog(id: "gid://shopify/Catalog/{{CatalogId}}") { id priceList {id prices(first:100, after:"{{After}}") {edges {cursor node {variant {id} price {amount} compareAtPrice {amount}}} pageInfo {hasNextPage}}}}}"}'

Some necessary nodes are missing in NextCatalogPrices. Here is a fixed request :

'{"query": "query { catalog(id: "gid://shopify/Catalog/{{CatalogId}}") { id priceList {id currency prices(first:100, after:"{{After}}") {edges {cursor node {variant {id product {id}} price {amount} compareAtPrice {amount}}} pageInfo {hasNextPage}}}}}"}'

#### Work Item(s) 
Fixes #27535

Fixes [AB#556528](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556528)

### CODE REVIEW

**Comment by onbuyuka** [comment]
@glachana could you please pull from main? looks like the builds are failing because branch is not up to date

**Comment by glachana** [comment]
@onbuyuka it should be fine now.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26432.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26895.

**Comment by AlexanderLundq** [comment]
@JesperSchulz hello! Sorry for asking but when referring to build ID, are u referring to the build ID of the Shopify Connector or the base app?

**Comment by JesperSchulz** [comment]
> 26895

All our Apps are currently built together and get the same Build ID. Both the BaseApp and the Shopify app should have a version with that ID. In this case we're referring to the following build: 25.2.26895.0 from the 19-11-2024.

**Pull request merged**
