### PR TITLE
Adding V2 API for sustainability account

### LINKED ISSUE #27508: Expose SustainabilityAccount table using a v2 Page API
### Describe the request

Add a v2 Page API to expose SustainabilityAccount table

### Additional context

This is required to read the Total emissions data from Business central

### PR DESCRIPTION
**Pull request by arvind1234**
#### Work Item(s) 
Fixes #27508

### CODE REVIEW

**Comment by arvind1234** [comment]
> @arvind1234 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="Microsoft"

**Review by AndersLarsenMicrosoft — COMMENTED** [review]
all good from my side

**Comment by onbuyuka** [comment]
Why? We already have this API: https://github.com/microsoft/ALAppExtensions/blob/main/Apps/W1/Sustainability/app/src/APIs/SustainabilityAccounts.Page.al

**Comment by onbuyuka** [comment]
Closing as we already have this API page.

**Pull request closed without merging**
