### PR TITLE
Event to skip reset Notify field on RecordLink.

### PR DESCRIPTION
**Pull request by auzhhv**

### CODE REVIEW

**Review by auzhhv — COMMENTED** [review]
Added event to be able to skip the reset of Notify field on RecordLink table after copying RecordLinks to a new table.

**Review by mazhelez — DISMISSED** [review]

**Comment by mazhelez** [comment]
@auzhhv before we can proceed with uptaking the PR, you need to agree to the _Contributor License Agreement_ (see comments from the bot above).

Additionally, I left a couple of more comments.

**Comment by auzhhv** [comment]
@microsoft-github-policy-service agree [company="Auzilium"]

**Comment by auzhhv** [comment]
@microsoft-github-policy-service agree company="Auzilium"

**Review by mazhelez — APPROVED** [review]

**Review by JesperSchulz — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47800.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 48026.

**Pull request merged**
