### PR TITLE
Add OnAfterValidateEmailMessage to allow performing tests before sending mail

### PR DESCRIPTION
**Pull request by fvet**
#12537

- Added OnAfterValidateEmailMessage publisher
- Moved all emailMessage validations into separate ValidateEmailMessage function.
- Raised OnAfterValidateEmailMessage publisher

### CODE REVIEW

**Review by GiorgosPa — CHANGES_REQUESTED** [review]
The only problem with this approach is that it allows changes to the email message just before it gets queued.

Please rename the event and place it just after the CreateOrUpdateEmailOutbox which will Queue the message for sending first method call.

**Comment by fvet** [comment]
Refactored the event to be raised on the email message has been queued in the email outbox (no longer allowed modification of the email message through the event)

PS: I'm not able to create test script. If MS could provide some walkthrough on how to easily apply changes to one submodule (Email) and publish / test on a Docker, I would be happy to contribute. Right now, I'm struggling in having al compiled / packages, since I lack the dotnet / dll's to work on the System app and cannot focus solely on the Email app. Also publishing the modified symbols (and running tests) on a Cronus docker did not work...

**Comment by pri-kise** [comment]
@fvet you can checkout the bcartifacts cache that is created on C:/ where the artifacts are copied to by the BCContainerHelper.
I had problems with those, too, but now everything compiles.

**Comment by fvet** [comment]
> @fvet you can checkout the bcartifacts cache that is created on C:/ where the artifacts are copied to by the BCContainerHelper.
> I had problems with those, too, but now everything compiles.

That's what I've tried by referencing the bc artifacts in the assemblyProbingPaths, but still 164 dotnet related errors...

image

**Comment by pri-kise** [comment]
@fvet did you reload VS Code?

**Comment by GiorgosPa** [comment]
Pleas make sure to add -includeAL on your docker command. Here is the [docs ](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-set-up-an-environment) we have on setting up your environment
last time it was possible to compile and publish both System and System Tests

```$containerName = 'mydemo'
        $password = 'P@ssw0rd'
        $securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
        $credential = New-Object pscredential 'admin', $securePassword
        $auth = 'UserPassword'
        $artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -country 'w1' -select 'Latest'
        $licenseFile = '<Path to license file>'
        New-BcContainer -accept_eula `
            -containerName $containerName `
            -credential $credential `
            -auth $auth `
            -artifactUrl $artifactUrl `
            -includeTestToolkit `
            -includeTestLibrariesOnly `
            -licenseFile $licenseFile `
            -includeAL -doNotExportObjectsToText `
            -updateHosts```

> > @fvet you can checkout the bcartifacts cache that is created on C:/ where the artifacts are copied to by the BCContainerHelper.
> > I had problems with those, too, but now everything compiles.
> 
> That's what I've tried by referencing the bc artifacts in the assemblyProbingPaths, but still 164 dotnet related errors...
> 
> ![image](https://user-images.githubusercontent.com/25268332/120162511-c10f7d00-c1f8-11eb-8de8-3ffb30c9d35a.png)

**Comment by GiorgosPa** [comment]
@fvet You get these problems because of the ordering of the paths. You need the following ordering:

1. DotNet framework
2. Business Central assemblies
3. Windows Assemblies

```
"al.assemblyProbingPaths": [
        "C:/NugetCache/NET_Framework_48_TargetingPack.4.8.3761",
        "C:/bcartifacts.cache/onprem/18.0.23013.23795",
        "C:/WINDOWS/assembly"
    ]
```

**Comment by pri-kise** [comment]
@GiorgosPa thanks for the carification. Is this anywhere documented in details? I couldn't find any information about this specifice setup for the `"al.assemblyProbingPaths"` and that the ordering might be important.
I asked for more documentation on this topic in the repository for documentation.
If there is already an offical documenation on how to setup the local environment, it would be very usefull if this information will be added for easier contritubtions in the future.
Best Regards
Kilian

**Comment by GiorgosPa** [comment]
@pri-kise No it is not documented yet, I have posted our official document for setting up the environment above, we will update the documentation soon.

**Review by GiorgosPa — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by fvet** [comment]
> "al.assemblyProbingPaths": [
>         "C:/NugetCache/NET_Framework_48_TargetingPack.4.8.3761",
>         "C:/bcartifacts.cache/onprem/18.0.23013.23795",
>         "C:/WINDOWS/assembly"
>     ]

_For my future reference_
Thanks, I'm now able to compile with following settings:

{
    "al.assemblyProbingPaths": [                
        "C:/Windows/Microsoft.NET/Framework64/v4.0.30319",
        "C:/bcartifacts.cache/sandbox/18.1.24822.25642",        
        "C:/WINDOWS/assembly"
    ]
}

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.

**Pull request merged**
