### PR TITLE
Add Include function to ABS Optional Parameters

### PR DESCRIPTION
**Pull request by GTimmers**
This PR will add an Include function to ABS Optional Parameters.
You can add a value as text that will be set as a value to the include parameter.
A unit test is also added.

### CODE REVIEW

**Comment by GTimmers** [comment]
> @GTimmers please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="{Cegeka}"]

**Comment by pri-kise** [comment]
This PR looks good to me.
The functionality includes a new test. and a Comment tag was added to the new procedure.
@darjoo is this something you can look at or who is responsible for integrations with external systems on the system application?

**Comment by JesperSchulz** [comment]
Let's try to get this in in time for 2023 Wave 2!

**Review by JesperSchulz — APPROVED** [review]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11768.

**Pull request merged**
