### PR TITLE
Performance Profiler tests

### PR DESCRIPTION
**Pull request by adrogin**
Extend test coverage for the performance profiler:
1. Add a test for the call tree with multiple child nodes of the same parent;
2. New tests for chart data.

### CODE REVIEW

**Comment by adrogin** [comment]
@microsoft-github-policy-service agree

**Review by IhorHandziuk — APPROVED** [review]
Great addition, thanks for improving our code coverage 🙂

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48857.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 49470.

**Pull request merged**
